version: '3.8'

services:
  auctionui:
    container_name: auctionui
    build: .
    #command: sh -c "sleep 30s ; python3 ./rest_api.py"
    ports:
      - 127.0.0.1:3000:3000
    pull_policy: always
    restart: unless-stopped